name: Build and test

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org/
          
    - name: Install lib dependencies
      run: cd ./projects/dxc-ngx-cdk && rm -rf node_modules && npm install

    - name: Install app dependencies
      run: cd . && npm install
    
    - name: Generate lib
      run: cd ./projects/dxc-ngx-cdk && npm run generate-lib

    - name: Link lib
      run: cd . && npm run link-lib
        
    - name: Test library Forms
      run: cd ./projects/dxc-ngx-cdk && npm run test-forms

    - name: Test library Navigation
      run: npm run test-navigations

    - name: Test library Layout
      run: npm run test-layout

    - name: Test library Utilities
      run: npm run test-utilities

    - name: Build angular cdk site
      run: cd . && npm run build-next-cdk-site